- name: print variables
  hosts: web
  vars:
    COURSE: "Devops with AWS"
    DURATION: 120HRS
    TRAINER: "Siva Kumar"
  tasks:
  - name: print the variables 
    ansible.builtin.debug:
      msg: "Course is {{ COURSE }} Duration is {{ DURATION }} and Trainer is {{ TRAINER }}"

      
