- name: Variables
  hosts: local
  connection: local
  vars:
    #COURSE: "Devops with AWS"
    COURSE: ansible
    DURATION: 120HRS
    TRAINER: Sivakumar
  tasks:
    - name: printing variables 
      ansible.builtin.debug:
        msg: "Course is {{ COURSE }} duration is {{ DURATION }} and Trainer is {{ TRAINER }}"

