- name: print Play and Task variables
  hosts: local
  connection: local
  vars:
    COURSE: "Devops With AWS"
    DURATION: 120HRS
    TRAINER: "Siva Kumar"
  tasks:
    - name: print tasks variables
      vars:
        COURSE: "ansible"
      ansible.builtin.debug:
        msg: "Course is {{ COURSE }} Duration is {{ DURATION }} and the Trainer is {{ TRAINER }}"
  tasks:
    - name: print Play Level variables
      ansible.builtin.debug:
        msg: "Course is {{ COURSE }} Duration is {{ DURATION }} and the Trainer is {{ TRAINER }}"
