- name: variables from file
  hosts: web
  tasks:
    vars_file:
    - Course.yaml
    - name: printing variables from file 
      ansible.builtin.debug:
        msg: "Course is {{ COURSE }} Duration is {{ DURATION }} and the Trainer is {{ TRAINER }}"
        