- name: variables from file
  hosts: web
  vars_files:
    - 08-Course.yaml
  tasks:
    - name: printing variables from file 
      ansible.builtin.debug:
        msg: "Course is {{ COURSE }} Duration is {{ DURATION }} and the Trainer is {{ TRAINER }}"
