- name: variables from inventory
  hosts: local
  connection: local
  tasks:
    - name: print variables from inventory file 
      ansible.builtin.debug:
        msg: "Course is {{ COURSE }} Duration is {{ DURATION }} and the Trainer is {{ TRAINER }}"