- name: variable preferences 
  hosts: local 
  connection: local
  # vars:
  #   GREET: "PLAY"
  vars_files:
    - Course.yaml
  # vars_prompt:
  #   - name: GREET
  #     prompt: Please enetr greet value as prompt
  tasks:
    - name: Task Variables 
      # vars: 
      #   GREET: "TASK"
      ansible.builtin.debug:
        msg: "Hello from {{ GREET }}"


# Variables Preferences 

#1. Command line or args
#2. Task level
#3. Files
#4. Prompt
#5. Play
#6. Inventory
#7. Roles
  