- name: variable preferences 
  hosts: local 
  connection: local
  vars:
    GREET: "PLAY"
  vars_files:
    - Course.yaml
  vars_prompt:
    - name: GREET
      prompt: Please enetr greet value as prompt
  tasks:
    - name: Task Variables 
      # vars: 
      #   GREET: "TASK"
      ansible.builtin.debug:
        msg: "Hello from {{ GREET }}"
  