- name: install packages 
  hosts: web
  become: yes 
  tasks:
    - name: install multiple packages
      ansible.builtin.package:
        name: "{{ item.name }}"
        state: "{{ item.state }}"
      loop:
        - { name: 'git', state: 'installed' }
        - { name: 'gcc', state: 'installed' }
        - { name: 'zip', state: 'installed' }