- name: filters 
  hosts: local
  connection: local
  tasks:
    - name: define undefined varaible
      ansible.builtin.debug:
        msg: "Hello {{ Person | default('Ramu')}}"

    - name: convert string into list
      vars: 
        fruits: "Apple, Banana, Mango, Cherry" 
      ansible.builtin.debug:
        msg: "Friuts are: {{ fruits | split(',')}}"
    - name: convert map into list 
      vars:
        course:
          name: ramu
          surname: gorla
          age: 27
      ansible.builtin.debug:
        msg: "course is: {{ course | dict2items }}"

    - name: convert list into map 
      vars: 
        course:
        - {'key': 'name', 'value': 'ramu'}
        - {'key': 'surname', 'value': 'gorla'}
        - {'key': 'age', 'value': 27}
      ansible.builtin.debug:
        msg: "List is {{ course | items2dict }}"

    - name: print lower case 
      vars: 
        name: "SIVAKUMAR"
      ansible.builtin.debug:
        msg: "{{ name | lower }}"

    - name: print upper case 
      vars: 
        name: "ramugorla.G"
      ansible.builtin.debug:
        msg: "{{ name | upper }}"

    - name: print min and max values 
      vars: 
        numbers: [1, 2, 0, 23, 350]
      ansible.builtin.debug:
        msg: "Min is {{ numbers | min }} Max is {{ number | max }}"
