3.90.209.40


[frontend]
3.90.209.40
3.90.209.40

[backend]
3.90.209.40
3.90.209.40
3.90.209.40
3.90.209.40

[parent:children]
frontend
backend

[web]
172.31.24.158 COURSE="DevOps with AWS" TRAINER="Sivakumar Reddy" DURATION="120HRS" ansible_user=ec2-user ansible_password=DevOps321
; localhost COURSE="DevOps with AWS" TRAINER="Sivakumar Reddy" DURATION="120HRS" ansible_user=ec2-user ansible_password=DevOps321

[local]
localhost

[local:vars]
COURSE="DevOps with Cloud"
TRAINER="Sivakumar Reddy"
DURATION="120HRS"
